# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20170916_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
