# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_work_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='category_slug',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='work_title',
            field=models.CharField(max_length=100),
        ),
    ]
